### ISSUE TITLE
Mistake in a_ij coefficient?

### ISSUE THREAD

**Issue by stepanzh** [vvpisarev/CubicEoS.jl#5]
https://github.com/vvpisarev/CubicEoS.jl/blob/eb7655f1763b65b82068be9f56640a76e2e7f874/src/basic_thermo.jl#L128

`a_ij = (1 - c_ij) sqrt(a_i a_j)`, `c_ij = e_ij + g_ij T + h_ij T^2`

Minus `.-` before `(temp^2) .* hij` instead of `.+`.

**Comment by stepanzh** [comment]
Notice, that in hydro-jl source there are *brackets*

https://gitlab.com/stepanzh/hydro-jl/-/blob/master/src/phys/eos/brusilovsky.jl#L337

**Comment by vvpisarev** [comment]
Fixed by https://github.com/vvpisarev/CubicEoS.jl/commit/ecff5a0b8d5166e907f1a0f963457ddcd7a807f0
